// Generated by scripts/gen_submit.py. Do not edit directly.
#include<cassert>
#include<iostream>
#include<vector>
#include<array>
#include<bitset>
#include<optional>
#include<algorithm>
#include<queue>
#include<fstream>
#include<string>
#include<iomanip>

/* BEGIN src/common.h */
extern int map_size;

struct Pos{
  int i,j;
  Pos(int _i,int _j)
    :i(_i)
    ,j(_j){

    }

  Pos operator+(const Pos& other) const{
    return Pos(i+other.i,j+other.j);
  }

  Pos operator-(const Pos& other) const{
    return Pos(i-other.i,j-other.j);
  }

  bool operator==(const Pos& other) const{
    return i==other.i && j==other.j;
  }

  bool operator!=(const Pos& other) const{
    return i!=other.i || j!=other.j;
  }

  bool is_on_map() const{
    return i>=0 && i<map_size && j>=0 && j<map_size;
  }



  int manhattan_distance(const Pos& other) const{
    return std::abs(i-other.i)+std::abs(j-other.j);
  }
};


enum ActionType{
  MOVE,
  SLIDE,
  CHANGE
};

const std::array<char,3> ACTIONS_CHAR={
  'M',
  'S',

  'A'
};

enum class Direction{
  UP,
  DOWN,
  RIGHT,
  LEFT
};

const std::array<char,4> DIRS_CHAR={
  'U',
  'D',
  'R',
  'L'
};


struct ActionRecord{
  ActionType type;
  Pos pos=Pos(-1,-1);
  Direction dir=Direction::UP;
};

const std::array<Pos,4> DIRS={
  Pos(-1,0),
  Pos(1,0),
  Pos(0,1),
  Pos(0,-1)
};

inline Direction get_direction(const Pos& from,const Pos& to){
  Pos diff=to-from;
  for(int i=0;i<static_cast<int>(DIRS.size());i++){
    if(DIRS[i]==diff){
      return static_cast<Direction>(i);
    }
  }
  assert(false);
  return Direction::UP;
}
/* END src/common.h */
/* BEGIN src/navigator.h */
class Navigator{
  public:
    Navigator(std::vector<Pos> blocks);
    ~Navigator()=default;

    std::vector<ActionRecord> bfs(Pos from,Pos to) const;
    void change_block(const Pos& pos);
    bool get_block(const Pos& pos) const;

  private:

    std::optional<Pos> move(const Pos& from,Direction dir) const;
    std::optional<Pos> slide(const Pos& from,Direction dir) const;

    static constexpr int N=20;
    int index(const Pos& pos) const{
      return pos.i*N+pos.j;
    }


    std::bitset<N*N> blocks_;
    std::array<std::vector<int>,N> row_blocks_;
    std::array<std::vector<int>,N> col_blocks_;
};
/* END src/navigator.h */
/* BEGIN src/navigator.cpp */
Navigator::Navigator(std::vector<Pos> blocks)
  :blocks_()
  ,row_blocks_()
  ,col_blocks_()
{

  for(const auto& block:blocks){
    change_block(block);
  }
}



std::vector<ActionRecord> Navigator::bfs(Pos from,Pos to) const{
  using namespace std;
  vector<vector<int>> dist(map_size,vector<int>(map_size,-1));
  vector<vector<ActionRecord>> pre(map_size,vector<ActionRecord>(map_size));

  queue<Pos> q;
  dist[from.i][from.j]=0;
  q.push(from);

  while(!q.empty()){
    Pos now=q.front();
    int d=dist[now.i][now.j];
    q.pop();

    if(now==to){
      break;
    }


    for(int k=0;k<DIRS.size();k++){

      const Direction dir=static_cast<Direction>(k);
      auto next=move(now,dir);
      if(!next){
        continue;
      }
      if(dist[next->i][next->j]!=-1){
        continue;
      }

      q.push(*next);
      dist[next->i][next->j]=d+1;

      pre[next->i][next->j]=ActionRecord{ActionType::MOVE,now,dir};
    }


    for(int k=0;k<DIRS.size();k++){

      const Direction dir=static_cast<Direction>(k);
      auto next=slide(now,dir);
      if(!next){
        continue;
      }
      if(dist[next->i][next->j]!=-1){
        continue;
      }

      q.push(*next);
      dist[next->i][next->j]=d+1;

      pre[next->i][next->j]=ActionRecord{ActionType::SLIDE,now,dir};
    }
  }


  if(dist[to.i][to.j]==-1){
    return {};
  }

  vector<ActionRecord> path;
  Pos cur=to;
  while(cur!=from){
    const ActionRecord record=pre[cur.i][cur.j];

    path.push_back(record);
    cur=record.pos;
  }
  reverse(path.begin(),path.end());
  return path;
}


void Navigator::change_block(const Pos& pos){
  assert(pos.is_on_map());

  auto& row=row_blocks_[pos.i];
  auto row_it=std::lower_bound(row.begin(),row.end(),pos.j);

  auto& col=col_blocks_[pos.j];
  auto col_it=std::lower_bound(col.begin(),col.end(),pos.i);

  const int block_index=index(pos);
  if(!blocks_.test(block_index)){
    row.insert(row_it,pos.j);
    col.insert(col_it,pos.i);
  }else{
    assert(row_it!=row.end() && *row_it==pos.j);
    assert(col_it!=col.end() && *col_it==pos.i);
    row.erase(row_it);
    col.erase(col_it);
  }

  blocks_.flip(block_index);

}

std::optional<Pos> Navigator::move(const Pos& pos,Direction dir) const{
  Pos next=pos+DIRS[static_cast<int>(dir)];
  if(!next.is_on_map()){
    return std::nullopt;
  }

  if(get_block(next)){
    return std::nullopt;
  }

  return next;
}

std::optional<Pos> Navigator::slide(const Pos& pos,Direction dir) const{

  Pos next=pos+DIRS[static_cast<int>(dir)];
  if(!next.is_on_map()||get_block(next)){
    return std::nullopt;
  }
  next=pos;
  switch(dir){

    case Direction::UP:{
      const auto& col=col_blocks_[pos.j];

      auto iter=std::lower_bound(col.begin(),col.end(),pos.i);
      if(iter==col.begin()){
        next.i=0;
      }else{
        --iter;
        next.i=*iter+1;
      }
      break;

    }
    case Direction::DOWN:{
      const auto& col=col_blocks_[pos.j];
      auto iter=std::upper_bound(col.begin(),col.end(),pos.i);
      if(iter==col.end()){
        next.i=map_size-1;
      }else{
        next.i=*iter-1;
      }
      break;

    }
    case Direction::RIGHT:{
      const auto& row=row_blocks_[pos.i];
      auto iter=std::upper_bound(row.begin(),row.end(),pos.j);
      if(iter==row.end()){
        next.j=map_size-1;
      }else{
        next.j=*iter-1;
      }
      break;

    }
    case Direction::LEFT:{
      const auto& row=row_blocks_[pos.i];
      auto iter=std::lower_bound(row.begin(),row.end(),pos.j);
      if(iter==row.begin()){
        next.j=0;
      }else{
        --iter;
        next.j=*iter+1;
      }
      break;

    }
    default:
      assert(false);
  }


  if(next==pos){
    return std::nullopt;
  }

  return next;
}

bool Navigator::get_block(const Pos& pos) const{
  return blocks_.test(index(pos));
}
/* END src/navigator.cpp */
/* BEGIN src/logger.h */
class Logger{
  public:
    Logger(const std::string& path);

    void log(const std::string& s);
    void log(const Navigator& state);
  private:
    std::ofstream ofs_;
};
/* END src/logger.h */
/* BEGIN src/logger.cpp */
Logger::Logger(const std::string& path)
  :ofs_(path)
{

}

void Logger::log(const std::string &s){
  ofs_<<s<<'\n';
}

void Logger::log(const Navigator& state){
}
/* END src/logger.cpp */
/* BEGIN src/strategy/strategy.h */
class Strategy{
  public:
    Strategy(std::vector<Pos> distinations);
    virtual ~Strategy();

    virtual std::vector<ActionRecord> solve(Navigator& navigator,Logger& logger);

  protected:
    std::vector<Pos> distinations_;
};
/* END src/strategy/strategy.h */
/* BEGIN src/strategy/strategy.cpp */
Strategy::Strategy(std::vector<Pos> distinations)
  :distinations_(distinations)
{

}

Strategy::~Strategy()=default;

std::vector<ActionRecord> Strategy::solve(Navigator& navigator,Logger& logger){
  (void)navigator;
  (void)logger;

  return{};
}
/* END src/strategy/strategy.cpp */
/* BEGIN src/strategy/greedy.h */
class Greedy : public Strategy{
  public:
    Greedy(std::vector<Pos> distinations);
    ~Greedy() override;

    std::vector<ActionRecord> solve(Navigator& navigator,Logger& logger) override;
};
/* END src/strategy/greedy.h */
/* BEGIN src/strategy/greedy.cpp */
Greedy::Greedy(std::vector<Pos> distinations)
  :Strategy(distinations)
{

}

Greedy::~Greedy()=default;

std::vector<ActionRecord> Greedy::solve(Navigator& navigator, Logger& logger){

  std::vector<ActionRecord> result;
  if(distinations_.empty()){
    return result;
  }

  Pos current=distinations_.front();
  for(size_t i=1;i<distinations_.size();i++){
    const Pos target=distinations_[i];
    std::vector<ActionRecord> path=navigator.bfs(current,target);

    logger.log(
      "from: ("+std::to_string(current.i)+","+std::to_string(current.j)+") "
      "to: ("+std::to_string(target.i)+","+std::to_string(target.j)+") "
      "num of path: "+std::to_string(path.size())
    );
    result.insert(result.end(),path.begin(),path.end());
    current=target;
  }



  return result;
}
/* END src/strategy/greedy.cpp */
/* BEGIN src/strategy/initial_position.h */
class InitialPosition : public Strategy{
  public:
    InitialPosition(std::vector<Pos> distinations);
    ~InitialPosition() override;

    std::vector<ActionRecord> solve(Navigator& navigator,Logger& logger) override;

};
/* END src/strategy/initial_position.h */
/* BEGIN src/strategy/initial_position.cpp */
namespace{
bool append_path_or_fail(
  std::vector<ActionRecord>& result,
  Logger& logger,
  const std::vector<ActionRecord>& path,
  const Pos& current,
  const Pos& target,
  const std::string& label
){
  logger.log(
    label+"\n"
    "from: ("+std::to_string(current.i)+","+std::to_string(current.j)+") "
    "to: ("+std::to_string(target.i)+","+std::to_string(target.j)+") "
    "num of path: "+std::to_string(path.size())
  );

  if(path.empty() && current!=target){
    logger.log("unreachable");
    return false;
  }

  result.insert(result.end(),path.begin(),path.end());
  return true;
}
}

InitialPosition::InitialPosition(std::vector<Pos> distinations)
  :Strategy(distinations)
{

}

InitialPosition::~InitialPosition(){

}

std::vector<ActionRecord> InitialPosition::solve(Navigator& navigator,Logger& logger){
  std::vector<ActionRecord> result;
  if(distinations_.empty()){
    return result;
  }
  std::vector<Pos> block_pos={

    Pos(9, 9),
    Pos(10,10),
    Pos(3, 9),
    Pos(16,10),
    Pos(9, 3),
    Pos(10,16),
  };

  Pos current=distinations_.front();

  for(const auto& b:block_pos){
    const Pos target=b+Pos(0,-1);
    std::vector<ActionRecord> path=navigator.bfs(current,target);


    if(!append_path_or_fail(result,logger,path,current,target,"block")){
      continue;
    }
    current=target;


    navigator.change_block(b);
    result.emplace_back(ActionRecord{
      ActionType::CHANGE,
      current,
      Direction::RIGHT,
    });
  }


  for(size_t i=1;i<distinations_.size();i++){
    const Pos target=distinations_[i];


    if(navigator.get_block(target)){
      const Pos approach=target+Pos(0,-1);
      if(!approach.is_on_map() || navigator.get_block(approach)){
        logger.log("blocked destination has no left approach");
        break;
      }

      std::vector<ActionRecord> path=navigator.bfs(current,approach);
      if(!append_path_or_fail(result,logger,path,current,approach,"blocked destination")){
        break;
      }

      navigator.change_block(target);
      result.emplace_back(ActionRecord{
        ActionType::CHANGE,
        approach,
        Direction::RIGHT,
      });
      result.emplace_back(ActionRecord{
        ActionType::MOVE,
        approach,
        Direction::RIGHT,
      });
      result.emplace_back(ActionRecord{
        ActionType::MOVE,
        target,
        Direction::LEFT,
      });
      navigator.change_block(target);
      result.emplace_back(ActionRecord{
        ActionType::CHANGE,
        approach,
        Direction::RIGHT,
      });

      current=approach;
      continue;
    }

    std::vector<ActionRecord> path=navigator.bfs(current,target);

    if(!append_path_or_fail(result,logger,path,current,target,"destination")){
      break;
    }
    current=target;
  }

  logger.log("blocks\n");
  for(int i=0;i<map_size;i++){
    std::string l="";
    for(int j=0;j<map_size;j++){
      if(navigator.get_block(Pos(i,j))){
        l+=".";
      }else{
        l+="x";
      }
    }
    logger.log(l);
  }


  return result;
}
/* END src/strategy/initial_position.cpp */
/* BEGIN src/main.cpp */
int map_size=0;
int main(){
  int n,m;
  std::cin>>n>>m;

  map_size=n;
  std::vector<Pos> g;
  for(int i=0;i<m;i++){
    int a,b; std::cin>>a>>b;

    g.emplace_back(Pos(a,b));
  }

  Navigator navigator({});
  Logger logger("log.txt");

  InitialPosition strategy(g);
  std::vector<ActionRecord> result=strategy.solve(navigator,logger);

  for(const auto& r:result){
    std::cout<<ACTIONS_CHAR[static_cast<int>(r.type)]
      <<" "<<DIRS_CHAR[static_cast<int>(r.dir)]<<'\n';
  }

}
/* END src/main.cpp */
