#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ORDER = [
    "src/common.h",
    "src/state.h",
    "src/state.cpp",
    "src/logger.h",
    "src/logger.cpp",
    "src/strategy/strategy.h",
    "src/strategy/strategy.cpp",
    "src/strategy/greedy.h",
    "src/strategy/greedy.cpp",
    "src/simulator.h",
    "src/simulator.cpp",
    "src/main.cpp",
]

# @trace-pilot db44efb1ee85df76e6e5f558dff9e83c203504e5
LOCAL_INCLUDE_RE = re.compile(r'^\s*#include\s*"[^"]+"')
SYSTEM_INCLUDE_RE = re.compile(r"^\s*#include\s*<[^>]+>")
LINE_COMMENT_RE = re.compile(r"//.*$")


def split_includes_and_body(source: Path) -> tuple[list[str], list[str]]:
    includes: list[str] = []
    body: list[str] = []

    for line in source.read_text().splitlines():
        stripped = line.strip()
        if stripped == "#pragma once":
            continue
        if LOCAL_INCLUDE_RE.match(line):
            continue
        if SYSTEM_INCLUDE_RE.match(line):
            includes.append(line)
            continue
        body.append(LINE_COMMENT_RE.sub("", line).rstrip())

    while body and body[0] == "":
        body.pop(0)
    while body and body[-1] == "":
        body.pop()
    return includes, body


def render_translation_unit(output_path: Path) -> None:
    ordered_includes: list[str] = []
    seen_includes: set[str] = set()
    sections: list[str] = []

    for relative_path in SOURCE_ORDER:
        source_path = ROOT / relative_path
        includes, body = split_includes_and_body(source_path)

        for include in includes:
            if include not in seen_includes:
                seen_includes.add(include)
                ordered_includes.append(include)

        section_lines = [f"/* BEGIN {relative_path} */"]
        section_lines.extend(body)
        section_lines.append(f"/* END {relative_path} */")
        sections.append("\n".join(section_lines))

    lines: list[str] = []
    lines.append("// Generated by scripts/gen_submit.py. Do not edit directly.")
    lines.extend(ordered_includes)
    lines.append("")
    lines.extend(sections)
    lines.append("")

    output_path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a single-file submit.cpp for AtCoder.")
    parser.add_argument(
        "--output",
        default="submit.cpp",
        help="Path to the generated file. Default: submit.cpp",
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = ROOT / output_path

    render_translation_unit(output_path)


if __name__ == "__main__":
    main()

